version: '3.5'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/password.txt:/mosquitto/config/password.txt
      - ./mosquitto/acl.acl:/mosquitto/config/acl.acl

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    restart: always
#    ports:
#      - "8086:8086"
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_READ_USER=${INFLUXDB_READ_USER}
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
      - INFLUXDB_WRITE_USER=${INFLUXDB_WRITE_USERNAME}
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - influxdb-data:/var/lib/influxdb
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
      - GF_SECURITY_ADMIN_USER=${GF_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_SECURITY_ALLOW_EMBEDDING=true
#      - GF_SECURITY_COOKIE_SAMESITE=lax
#      - GF_LIVE_ALLOWED_ORIGINS=${GRAFANA_ALLOWED-ORIGIN}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    volumes:
     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
volumes:
  influxdb-data:
  grafana-data: