{
 "title": "PAX Detail",
 "time": { "from": "2022-01-24T14:30:16.555Z", "to": "2022-01-26T02:35:42.183Z" },
 "templating": {
  "list": [
   {
    "name": "paxNodeID",
    "query": "SHOW TAG VALUES  FROM \"pax\" WITH KEY = \"node_id\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "pax",
     "select": [
      [
       { "params": [ "latitude" ], "type": "field" }
      ],
      [
       { "params": [ "longitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "PAX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total in selected Time Range",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pax",
     "select": [
      [
       { "params": [ "pax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "PAX" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total in selected Time Range",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pax",
     "select": [
      [
       { "params": [ "pax" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
     ]
    }
   ]
  },
  {
   "title": "MacFilter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "pax",
     "query": "SHOW TAG VALUES WITH KEY = \"macfilter\" WHERE  (\"node_id\" =~ /^$paxNodeID$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
     ]
    }
   ]
  },
  {
   "title": "Last activity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pax",
     "select": [
      [
       { "params": [ "vbatt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
     ]
    }
   ]
  },
  {
   "title": "Compare measurements",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "node_id" ], "type": "tag" }
     ],
     "measurement": "pax",
     "query": "SELECT last(\"vbatt\") FROM \"pax\" WHERE (\"node_id\" =~ /^$paxNodeID$/)  GROUP BY \"node_id\"",
     "select": [
      [
       { "params": [ "vbatt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pax",
     "select": [
      [
       { "params": [ "vbatt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
     ]
    }
   ]
  },
  {
   "title": "PAX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "PAX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pax",
     "select": [
      [
       { "params": [ "pax" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
     ]
    }
   ]
  },
  {
   "title": "Explore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean Values (1h)",
     "type": "status-history",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "PAX" } },
     "targets": [
      {
       "alias": "PAX",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "node_id" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "pax",
       "select": [
        [
         { "params": [ "pax" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
       ]
      }
     ]
    },
    {
     "title": "Change (30m)",
     "type": "candlestick",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "30m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "pax",
       "select": [
        [
         { "params": [ "pax" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         },
         { "params": [ "first" ], "type": "alias" }
        ],
        [
         { "params": [ "pax" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "last" ], "type": "alias" }
        ],
        [
         { "params": [ "pax" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "max" ], "type": "alias" }
        ],
        [
         { "params": [ "pax" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         },
         { "params": [ "min" ], "type": "alias" }
        ],
        [
         { "params": [ "pax" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "vol" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "node_id", "operator": "=~", "value": "/^$paxNodeID$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}